# Generated by Django 3.1.3 on 2020-11-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da mãe')),
                ('born_date', models.DateField(blank=True, null=True, verbose_name='Dt. nascimento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Dt. óbito')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('rg_ssp', models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('ES', 'Espírito Santo')], max_length=2, null=True, verbose_name='SSP')),
                ('state', models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('ES', 'Espírito Santo')], max_length=2, null=True, verbose_name='Estado')),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço (linha 1)')),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço (linha 2)')),
                ('neighbourhood', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('residence_type', models.CharField(blank=True, choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1, null=True, verbose_name='Distrito')),
                ('private_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel. p/ contato')),
                ('message_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tel. p/ mensagem')),
                ('observation', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('T', 'Paciente'), ('P', 'Acompanhante'), ('V', 'Voluntário'), ('S', 'Serviços'), ('O', 'Outros')], max_length=1, verbose_name='Tipo de check-in')),
                ('treatment', models.CharField(blank=True, choices=[('Q', 'Quimioterapia'), ('R', 'Radioterapia'), ('S', 'Cirurgia'), ('E', 'Exames'), ('C', 'Consulta'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Motivo')),
                ('ca_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número C.A.')),
                ('social_vacancy', models.BooleanField(blank=True, null=True, verbose_name='Vaga Social?')),
                ('observation', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação')),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companion', to='people.person', verbose_name='Acompanhante')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_person', to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': "Check-in's",
            },
        ),
    ]
