# Generated by Django 3.1.3 on 2020-11-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.checkin')),
            ],
            options={
                'verbose_name': 'Check-out',
                'verbose_name_plural': "Check-out's",
            },
        ),
    ]
