# Generated by Django 3.1.3 on 2020-12-05 10:46

from django.db import migrations, models
import utils.phone.check_phone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='message_phone',
            field=models.CharField(blank=True, help_text='Exemplo: 99999-9999', max_length=10, null=True, validators=[utils.phone.check_phone.check_phone], verbose_name='Tel. p/ mensagem'),
        ),
    ]
