# Generated by Django 3.1.3 on 2020-11-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201128_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Pessoa'),
        ),
    ]
