# Generated by Django 3.1.3 on 2020-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201205_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
    ]
