# Generated by Django 3.1.3 on 2020-11-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201128_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.TextField(blank=True, max_length=600, null=True, verbose_name='Descrição')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Serviço de profissional',
                'verbose_name_plural': 'Serviços de profissional',
            },
        ),
    ]
