# Generated by Django 3.1.3 on 2020-12-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_checkin_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Check-in', 'verbose_name_plural': "Check-in's"},
        ),
    ]
