# Generated by Django 3.1.3 on 2020-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201128_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='reason',
            field=models.CharField(choices=[('T', 'Paciente'), ('P', 'Acompanhante'), ('F', 'Profissional'), ('V', 'Voluntário'), ('S', 'Visitantes'), ('O', 'Outros')], max_length=1, verbose_name='Tipo de check-in'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Rua e número da residência', max_length=100, null=True, verbose_name='Endereço (linha 1)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Complemento (apartamento, bloco,...)', max_length=100, null=True, verbose_name='Endereço (linha 2)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_date',
            field=models.DateField(blank=True, help_text='Exemplo: 03/12/2015', null=True, verbose_name='Dt. nascimento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, help_text='Exemplo: 000.000.000-00', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='message_phone',
            field=models.CharField(blank=True, help_text='Exemplo: (99) 9 9999-9999', max_length=30, null=True, verbose_name='Tel. p/ mensagem'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Exemplo: 00.000-000', max_length=15, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_phone',
            field=models.CharField(blank=True, help_text='Exemplo: (99) 9 9999-9999', max_length=30, null=True, verbose_name='Tel. p/ contato'),
        ),
    ]
